sonar.projectKey=haritz99_TFG_Gestion_Transporte
sonar.organization=haritz99

sonar.sources=frontend/lib,backend/app
sonar.dart.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=TFG_Gestion_Transporte
#sonar.projectVersion=1.0

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8