org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Propiedades para que los plugins de Flutter no fallen
flutter.minSdkVersion=24
flutter.targetSdkVersion=36
flutter.compileSdkVersion=36
