// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuP5Mr_durinwCXOwLet2Qrpt1du69ViI',
    appId: '1:462903431070:web:eec2a1c4f5bb8a3d1c508f',
    messagingSenderId: '462903431070',
    projectId: 'gestion-transporte-dev',
    authDomain: 'gestion-transporte-dev.firebaseapp.com',
    storageBucket: 'gestion-transporte-dev.firebasestorage.app',
    measurementId: 'G-JT849900DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyRodeQOSMvBu3dhKzpqw6Dn4JEuwLewM',
    appId: '1:462903431070:android:009e4435bd170e861c508f',
    messagingSenderId: '462903431070',
    projectId: 'gestion-transporte-dev',
    storageBucket: 'gestion-transporte-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwpXAXXtzNGnen3lefPrx72DaIOteeKZo',
    appId: '1:462903431070:ios:b66ad57de3c95ceb1c508f',
    messagingSenderId: '462903431070',
    projectId: 'gestion-transporte-dev',
    storageBucket: 'gestion-transporte-dev.firebasestorage.app',
    iosBundleId: 'com.example.myapp.dev',
  );
}
