// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNZaYZLh1MiLdSKQwqWHePpLlrAVFM7fw',
    appId: '1:772545103506:web:805d6c1f3317d2141b884b',
    messagingSenderId: '772545103506',
    projectId: 'gestion-transporte-stg',
    authDomain: 'gestion-transporte-stg.firebaseapp.com',
    storageBucket: 'gestion-transporte-stg.firebasestorage.app',
    measurementId: 'G-KX01KSQLLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqu5UzxVXOyjRkXLSxrgx8pJt27anVFNE',
    appId: '1:772545103506:android:b13e275166e822c91b884b',
    messagingSenderId: '772545103506',
    projectId: 'gestion-transporte-stg',
    storageBucket: 'gestion-transporte-stg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZtjT1-lSzEpbbXJp7BttpzCbM9IeF3lo',
    appId: '1:772545103506:ios:f5dd929e6a019aa11b884b',
    messagingSenderId: '772545103506',
    projectId: 'gestion-transporte-stg',
    storageBucket: 'gestion-transporte-stg.firebasestorage.app',
    iosBundleId: 'com.example.myapp.staging',
  );
}
